### PR TITLE
Added community logo files and updated guidelines

### PR DESCRIPTION
**Pull request by thecodejunkie**
We've previously talked about creating a separate logo that can be used by our community members when they want to use the Nancy logo to highlight their work in sites such as nuget.org

Since we (usually) use the black silhouette, on a white background, I decided to base the community logo on the inverted version.

Added ai, eps and png version + updated the guidelines

### CODE REVIEW

**Comment by thecodejunkie** [comment]
ping @NancyFx/most-valued-minions for feedback before we pull

**Comment by khellang** [comment]
LGTM! Can't pull though...

**Comment by horsdal** [comment]
LGTM. Really nice, actually

**Comment by jchannon** [comment]
YARP

**Comment by phillip-haydon** [comment]
Awesome stuff!

**Review by khellang — APPROVED** [review]

**Comment by khellang** [comment]
🎉

**Pull request merged**
